language: shell
#os:
#  - linux
#  - osx
#  - windows
#dist:
#  - bionic
#  - xenial
#  - trusty
#osx_image:
#  - xcode11
#  - xcode10.2
#  - xcode9.4
matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8.0
    - os: windows

before_script:
  - uname -a
  - env | sort
  - ls -l /bin/sh
  - /bin/sh --version || true # Allow failure
  - git --version
  # Print OS Version
  - if [ -e /etc/os-release ]; then cat /etc/os-release; fi
  - if which sw_vers > /dev/null 2>&1; then sw_vers; fi
  - if which cmd.exe > /dev/null 2>&1; then cmd.exe /C ver; fi
script:
  - ./gibo version
  # Measure performance of new version
  - ./gibo list
  - for i in {1..10}; do { time ./gibo list; } 2>> performance_new.txt; done
  # Measure performance of old version
  - git fetch origin master
  - git show 54015c2:gibo > gibo_old
  - chmod +x gibo_old
  - for i in {1..10}; do { time ./gibo_old list; } 2>> performance_old.txt; done
  # Output report
  - cat performance_new.txt
  - cat performance_old.txt
