language: shell
#os:
#  - linux
#  - osx
#  - windows
#dist:
#  - bionic
#  - xenial
#  - trusty
#osx_image:
#  - xcode11
#  - xcode10.2
#  - xcode9.4
matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: osx
      dist: xcode11
    - os: osx
      dist: xcode10.2
    - os: osx
      dist: xcode9.4
    - os: windows

before_script:
  - uname -a
  - env | sort
  - ls -l /bin/sh
  - /bin/sh --version || true # Allow failure
  - git --version
  # Print OS Version
  - if [ -e /etc/os-release ]; then cat /etc/os-release; fi
  - if which sw_vers > /dev/null 2>&1; then sw_vers; fi
  - if which cmd.exe > /dev/null 2>&1; then cmd.exe /C ver; fi
script:
  - ./gibo version
  - ./gibo list
